#!/bin/zsh
#
# .zshrc: Execute commands at the start of an interactive session.
#

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Clone antidote if necessary
if [[ ! -d ${ZDOTDIR:-$HOME}/.antidote ]]; then
  git clone --depth 1 https://github.com/mattmc3/antidote ${ZDOTDIR:-$HOME}/.antidote
fi

# Source/load antidote
source ${ZDOTDIR:-$HOME}/.antidote/antidote.zsh
antidote load

# Set zstyles as required
[[ ! -f ${ZDOTDIR:-$HOME}/.zstyles ]] || source ${ZDOTDIR:-$HOME}/.zstyles
